### PR TITLE
Support 2021.12.15s

### PR DESCRIPTION
**Pull request by Anusien**
Known issues:

- [x] When you drag the scrollbar in the game settings menu, it kind of vibrates
- [x] Custom hats don't load for some reason
- [x] I'm not sure where this version of Reactor is coming from
- [x] Need to update compatibility in the README
- [x] Need to thank Guus in the README
- [x] The auto-compile action on merge requests isn't passing anymore
- [x] If the Seer reveals an player who goes invisible, the Seer can see their role walking around (but not their name). Similarly, the Covert going invisible sees their own role but not their own name. Including in meetings.
- [x] Teleporter button is over the use button
- [ ] Sometimes the count of impostors on the intro screen is wrong (wonder if this is a Reactor Debugger only thing?)
- [ ] Modifiers are hard to see on the role assignment screen; they're very far at the bottom
- [x] Dead don't see roles during the day
- [x] Morphling doesn't have a Sample button
- [x] Glitch's Mimic and Hack buttons overlap
- [x] Mayor Abstain button doesn't have the right name
- [x] Morphling who is morphed sees themselves as the morphed person in the meeting
- [x] Can't set vision in increments of .125 anymore
- [ ] Reports that impostors can assassinate Snitch with only one task left
- [ ] Reports that Carnivore isn't getting their report info

### CODE REVIEW

**Comment by Anusien** [comment]
>  I'm not sure where this version of Reactor is coming from
When I tried using Reactor 1.2.0, which is the latest version and says it has support for the latest version of Among Us, I wasn't able to join any public games. I think it's because of an issue with the modded handshake. Reactor doesn't normally let you play on public servers; TOU does some dark magic to allow that to happen. When I copied the Reactor DLL used by TOU-R, it worked. That's what I have in 3.0.0-beta.1.

I think TOU-R is using [this version](https://github.com/NuclearPowered/Reactor/actions/runs/1584173029) of Reactor. It looks like Reactor team updated the code to support 2021.12.14s, but didn't issue a new tag. The difference between that and 1.2.0 is [this MR](https://github.com/NuclearPowered/Reactor/commit/89a8adadf73c5416bf802651e76cf6be7f342bed). I believe something in the server connection code is breaking that dark magic.

**Comment by VirusTLNR** [comment]
Just to add, the scrollbar vibrates even on the vanilla settings, so it maybe something for innersloth to fix.

**Comment by VirusTLNR** [comment]
phantom is seemingly broken, or something relating to it is broken

what i tested was...

4 players
1 impostor
1 crew
1 glitch
1 arsonist

killed the crew, reported the body,, skipped on the 3 alives.. game auto ended, was playing on mira...and then polus, and the same thing happened, Arsonist won without dousing.

impostor + glitch alive = game shouldent end.
arsonist doused no one = game shouldent be won by the arsonist.

i turn off the phantom, the game doesnt end, so its something about when the phantom is set after the meeting.

**Comment by VirusTLNR** [comment]
Played with my group last night.

Don't know if it's a new feature, or a bug, but someone complained that as engineer  they suddenly had reduced vision.

I didnt really get to play as I spent the whole evening helping others install the mod so I never got engineer so couldent check it myself

Beyond that as far as I know no one reported any bugs.

The only bug I had was the usual crash from the handshake bug... so seems that's the main 2 bugs..

1 phantom can't be spawned (at least not with 4 people left)
2 engineer vision being reduced mid game (feature added in if not a bug..)

Otherwise people were happy, aside from the engineer thing.

I'll try to look at the engineer thing if it's not meant to happen, but that will be later.

**Comment by Anusien** [comment]
Engineer’s vision is unaffected. Maybe they Button Barry’ed?

**Comment by VirusTLNR** [comment]
> Engineer’s vision is unaffected. Maybe they Button Barry’ed?

I knew I read something about vision reduction...

Anyway I get the feeling it was a bogus report, I tested and found nothing wrong with it.

So only things as far as I can see is


1- move modifier name up on intro (there is a pr for this)
2- handshake host crash bug (there is a pr for this.)

EDIT:- phantom game ending bug was just me being a moron, whoops!

People were saying "very buggy" but no one gave me details and because I wasn't really able to join in that session, I think the "buggy" is probably talking about the host crash bug as after I crashed as host I assume that's when they got the "buggyness".

**Pull request merged**
