### PR TITLE
fix(Phantom): Don't get stuck in Polus library vent

### LINKED ISSUE #121: Phantom spawning in Polus admin vent is stuck
If the Phantom spawns in the Admin vent on Polus, they will be stuck against the wall and can't ever leave.

Probably similar to the Teleporter issue, in that teleporting someone to the bottom of the vent will put them in the wall and you need to use the middle of the vent.

### PR DESCRIPTION
**Pull request by Anusien**
Fixes #121

### CODE REVIEW

**Comment by VirusTLNR** [comment]
erm? i already fixed this in my pull request xD

**Comment by Anusien** [comment]
Yeah but you told me your PR wasn’t mergeable because the Phantom task stuff wasn’t working.

**Comment by VirusTLNR** [comment]
no, i wrote that the pulll request is finished, and works.

all i said was it removes random tasks, and that if someone knows how to remove exactly the right type of tasks they can add to it.

edit:- my actual wording was i put in a calculation for removing the correct task types (long/short/common) but i didnt know how to perform that so set it to remove random tasks.

**Comment by VirusTLNR** [comment]
anyway, looking at your vent fix, looks better way of doing it than mine (as it applies it to all vents), but for reducing phantom tasks, should use the coding from that commit, as is, it works fine, but i just figured it would be better if it takes away tasks in a balanced manner rather than removing all the short tasks or something.

**Pull request merged**
