### PR TITLE
Give a discount to all the day1 cooldowns equal to the impostor's day1 kill cooldown discount

### PR DESCRIPTION
**Pull request by Anusien**
The functional change in this MR is to set the day 1 cooldowns. In the original version of Town of Us, the impostors all had a 10 second kill cooldown starting day1, so all the abilities were also set to a 10 second cooldown on day1. We made the change to allow players to set the initial impostor kill cooldown. This means that some abilities are wildly out of sync though; impostors can kill long before someone ever gets to use their ability. The fix is to give every cooldown a "discount" equal to the impostor kill discount. So if the impostor kill cooldown is 25s and the initial impostor kill cooldown is 15s, every other cooldown gets a discount of 10s to start the game.

This also eliminates the "Glitch Kill Cooldown" and "Initial Glitch Kill Cooldown" options in favor of syncing with the ones used by the impostors.

### CODE REVIEW

**Comment by VirusTLNR** [comment]
is this just changing all cooldowns to be the same? or allowing differences by relative change?

ie..

impostor kill cooldown = 30
morphling change cooldown -5 = 25
sheriff kill cooldown -5 = 25
glitch kill cooldown +5 = 35

and so on?

**Comment by Anusien** [comment]
Example:
Impostor cooldown = 25s
Initial Impostor cooldown = 15s
Seer cooldown = 40s
Sheriff cooldown = 22.5s

The initial seer cooldown will be 30s and the initial Sheriff cooldown will be 12.5s

**Comment by VirusTLNR** [comment]
so basically

impcooldown - impstartcooldown = cooldowndiff
seercooldown - cooldowndiff = seerstartcooldown

etc?

i figured this was more in relation to simplifying settings, on which note as ive mentioned previously, changing the impostor kill cooldown has ramification accross many settings (for example, sheriff is perhaps normally 5 seconds lower than imp cooldown, so if you lower imp cooldown, surely you need to lower the sheriff cooldown as well).

so my pov was.. either.. changing imp cooldown tweaks all the other settings automatically.. or.. you change the other cooldowns to be a +/- relative to the imp cooldown.

but if that is not what you include in refactoring the cooldowns then thats maybe something to think about for simplification in the future.

**Comment by Anusien** [comment]
Next steps after this ticket:
* Make the two-phase cooldowns (Morphling, Covert, Swooper, etc; all the abilities that you activate and run for a while before ending) a separate class
* Incorporate the button creation and management as part of the 1-phase cooldowns
* Incorporate the button creation and management as part of the 2-phase cooldowns

**Pull request merged**
